#!/usr/bin/env python3
"""Reproduce bounded browser/PWA/model packages from public, explicit source lists.

No installer, network client, account access or printer command is executed.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import math
from pathlib import Path
import stat
import struct
import sys
import zipfile
import zlib

VERSION = "1.0.0"
SHELL = (
    "index.html",
    "style.css",
    "core.js",
    "demo.js",
    "strict-json.js",
    "review.js",
    "offline.js",
    "privacy.html",
    "manifest.webmanifest",
    "icons/icon128.png",
    "icons/icon192.png",
    "icons/icon512.png",
    "LICENSE.txt",
)


def read(root: Path, path: str) -> bytes:
    """Read a bounded, regular in-repository source without following links."""
    target = root / path
    if not target.resolve().is_relative_to(root.resolve()):
        raise ValueError("Source escapes repository")
    for item in (target, *target.parents):
        if item == root:
            break
        if item.is_symlink() or getattr(item, "is_junction", lambda: False)():
            raise ValueError("Linked sources are not accepted")
    info = target.stat()
    if not stat.S_ISREG(info.st_mode) or info.st_size > 3 * 1024 * 1024:
        raise ValueError("Source is not a bounded regular file")
    return target.read_bytes()


def text(root: Path, path: str) -> bytes:
    return read(root, path).decode("utf-8").replace("\r\n", "\n").encode("utf-8")


def document(value: object) -> bytes:
    return (json.dumps(value, indent=2, ensure_ascii=False) + "\n").encode()


def icon(size: int) -> bytes:
    """Rasterize the project's existing pulse mark; no fonts or external assets."""
    points = [(18, 64), (34, 64), (44, 34), (64, 96), (80, 51), (88, 64), (110, 64)]
    raw = bytearray()
    for y in range(size):
        raw.append(0)
        for x in range(size):
            px, py = (x + 0.5) * 128 / size, (y + 0.5) * 128 / size
            distance = math.inf
            for (a, b), (c, d) in zip(points, points[1:]):
                t = max(
                    0,
                    min(
                        1, ((px - a) * (c - a) + (py - b) * (d - b)) / ((c - a) ** 2 + (d - b) ** 2)
                    ),
                )
                distance = min(distance, math.hypot(px - a - t * (c - a), py - b - t * (d - b)))
            raw.extend((116, 224, 191) if distance <= 4.5 else (17, 24, 33))

    def chunk(kind: bytes, value: bytes) -> bytes:
        return (
            struct.pack(">I", len(value))
            + kind
            + value
            + struct.pack(">I", zlib.crc32(kind + value))
        )

    # Uncompressed deflate makes generated bytes independent of compression tuning.
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 2, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(bytes(raw), 0))
        + chunk(b"IEND", b"")
    )


def archive(files: dict[str, bytes]) -> bytes:
    """Stable timestamp/order and explicit bytes; never crawl a private workspace."""
    out = io.BytesIO()
    with zipfile.ZipFile(out, "w", compression=zipfile.ZIP_STORED) as handle:
        for name, content in sorted(files.items()):
            entry = zipfile.ZipInfo(name, (2026, 9, 17, 0, 0, 0))
            entry.external_attr = 0o100644 << 16
            handle.writestr(entry, content)
    return out.getvalue()


def build(root: Path) -> dict[str, bytes]:
    """Create standalone assets with canonical-engine parity and scoped caching."""
    source = "distribution/reviewer/"
    app = {
        name: text(root, source + name)
        for name in ("index.html", "strict-json.js", "review.js", "offline.js", "privacy.html")
    }
    for name in ("core.js", "demo.js", "style.css"):
        app[name] = text(root, "reference/" + name)
    app["style.css"] += (
        b"\nheader {flex-wrap:wrap;} pre {white-space:pre-wrap;overflow-wrap:anywhere;} a {color:#86cdbf;} [hidden] {display:none!important;} .badge {white-space:normal;}\n"
    )
    app["LICENSE.txt"] = text(root, "LICENSES/MIT-reference.txt")
    for n in (16, 32, 48, 128, 192, 512):
        app[f"icons/icon{n}.png"] = icon(n)
    app["manifest.webmanifest"] = document(
        {
            "id": "./",
            "name": "KlipperLearn Calibration Review",
            "short_name": "KL Review",
            "description": "Local calibration evidence review; no printer connection or AI API.",
            "start_url": "./index.html",
            "scope": "./",
            "display": "standalone",
            "background_color": "#111821",
            "theme_color": "#111821",
            "icons": [
                {
                    "src": f"icons/icon{n}.png",
                    "sizes": f"{n}x{n}",
                    "type": "image/png",
                    "purpose": "any",
                }
                for n in (192, 512)
            ],
        }
    )
    shell_digest = hashlib.sha256(b"".join(app[name] for name in SHELL)).hexdigest()[:12]
    worker = """/* SPDX-License-Identifier: MIT. Cache public shell files only, never input data. */
'use strict';
const CACHE = 'klipperlearn-review-shell-__DIGEST__';
const SHELL = __SHELL__;
const allowed = new Set(SHELL.map(name => new URL(name, self.registration.scope).href));
self.addEventListener('install', event => event.waitUntil((async () => {
  const cache = await caches.open(CACHE);
  await cache.addAll([...allowed]);
  await self.skipWaiting();
})()));
self.addEventListener('activate', event => event.waitUntil((async () => {
  for (const key of await caches.keys()) if (key.startsWith('klipperlearn-review-shell-') && key !== CACHE) await caches.delete(key);
  await self.clients.claim();
})()));
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  let url = new URL(event.request.url);
  if (url.href === self.registration.scope) url = new URL('index.html', self.registration.scope);
  if (!allowed.has(url.href)) return;
  event.respondWith((async () => (await caches.open(CACHE)).match(url.href).then(hit => hit || fetch(event.request)))());
});
""".replace("__DIGEST__", shell_digest).replace("__SHELL__", json.dumps(SHELL))
    app["service-worker.js"] = worker.encode()
    result = {"docs/review/" + name: data for name, data in app.items()}
    common = {
        k: v
        for k, v in app.items()
        if k not in ("service-worker.js", "manifest.webmanifest", "offline.js")
        and k not in ("icons/icon192.png", "icons/icon512.png")
    }
    common["index.html"] = (
        common["index.html"]
        .replace(b'<link rel="manifest" href="manifest.webmanifest">\n', b"")
        .replace(b'<script src="offline.js" defer></script>\n', b"")
        .replace(
            b"connect-src 'self'; worker-src 'self'; manifest-src 'self';",
            b"connect-src 'none'; worker-src 'none';",
        )
    )
    common["background.js"] = text(root, source + "background.js")
    manifest = {
        "manifest_version": 3,
        "name": "KlipperLearn Calibration Review",
        "version": VERSION,
        "description": "Review local 3D-print calibration trials, export advisor requests and validate bounded proposals. No printer access.",
        "icons": {str(n): f"icons/icon{n}.png" for n in (16, 32, 48, 128)},
        "action": {
            "default_title": "Open local calibration reviewer",
            "default_icon": {str(n): f"icons/icon{n}.png" for n in (16, 32)},
        },
        "permissions": [],
        "content_security_policy": {
            "extension_pages": "default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self'; connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'"
        },
    }
    for family in ("Firefox", "Chromium"):
        metadata = dict(manifest)
        if family == "Firefox":
            metadata["background"] = {"scripts": ["background.js"]}
            metadata["browser_specific_settings"] = {
                "gecko": {
                    "id": "calibration-review@klipperlearn.agnuxo1.github.io",
                    "strict_min_version": "140.0",
                    "data_collection_permissions": {"required": ["none"]},
                },
                "gecko_android": {"strict_min_version": "142.0"},
            }
        else:
            metadata["background"] = {"service_worker": "background.js"}
        files = {**common, "manifest.json": document(metadata)}
        result[f"distribution/packages/KlipperLearn-Calibration-Review-{family}-{VERSION}.zip"] = (
            archive(files)
        )
    result[f"distribution/packages/KlipperLearn-Calibration-Review-Web-{VERSION}.zip"] = archive(
        app
    )
    model = {
        name: text(root, "distribution/model/" + name)
        for name in ("README.md", "LISTING.md", "trial-worksheet.csv")
    }
    model["adjustment-card.stl"] = read(root, "src/klipperlearn/mobile_app/adjustment-card.stl")
    model["COPYING"] = text(root, "COPYING")
    model["LICENSE"] = text(root, "LICENSE")
    model["asset.json"] = document(
        {
            "name": "KlipperLearn original adjustment card",
            "size_mm": [40, 30, 12],
            "triangles": 7756,
            "sha256": hashlib.sha256(model["adjustment-card.stl"]).hexdigest(),
            "origin": "Agnuxo1/KlipperLearn canonical published asset",
            "license": "GPL-3.0-or-later",
            "physical_print_verified_for_this_exact_asset": False,
            "matching_photograph_included": False,
            "ai_assisted_design": True,
            "exclusive_distribution": False,
            "printer_gcode_included": False,
        }
    )
    result["distribution/packages/KlipperLearn-Calibration-Card-Community-Kit.zip"] = archive(model)
    records = [
        {
            "file": key.split("/")[-1],
            "bytes": len(value),
            "sha256": hashlib.sha256(value).hexdigest(),
        }
        for key, value in sorted(result.items())
        if key.startswith("distribution/packages/")
    ]
    result["distribution/packages/manifest.json"] = document(
        {
            "schema": "klipperlearn.distribution-bundles/v1",
            "version": VERSION,
            "store_signed": False,
            "store_published": False,
            "packages": records,
        }
    )
    result["distribution/packages/SHA256SUMS"] = "".join(
        r["sha256"] + "  " + r["file"] + "\n" for r in records
    ).encode()
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    assets = build(root)
    if args.check:
        mismatches = [
            name
            for name, raw in assets.items()
            if not (root / name).is_file() or (root / name).read_bytes() != raw
        ]
        if mismatches:
            print("Generated asset mismatch: " + ", ".join(mismatches), file=sys.stderr)
            return 1
        print("Browser/PWA/model artifacts match their canonical public sources.")
    else:
        for name, raw in assets.items():
            target = root / name
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(raw)
        print("Built unsigned browser bundles, opt-in offline PWA and original model kit.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
